# Generated by Django 3.0.8 on 2020-08-10 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_auto_20200810_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='giving',
            name='designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tith',
            name='designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
