# Generated by Django 3.0.8 on 2020-08-11 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_auto_20200810_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communication',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preachingvideo',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preachingvideo',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
